services:
  slim:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - .:/var/www
      - logs:/var/www/logs

  composer:
    image: composer:2
    working_dir: /app
    volumes:
      - .:/app

volumes:
  logs:
